version: "3"
services:

  postgres:
    build:
      context: ./postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  jupyter:
    build:
      context: ../
      dockerfile: ./env/jupyter/.
    env_file:
      - ../env/jupyter/.env
    ports:
      - "8888:8888"
    links:
      - postgres
    volumes:
          - "./notebooks:/notebooks"
          - "./data:/data"
